### ISSUE TITLE
Securing communication between client and registry over an untrusted TLS endpoint

### ISSUE THREAD

**Issue by BavoNootaert** [erasmus-without-paper/ewp-specs-architecture#27]
Encryption is used in the case where the TLS endpoint is untrusted (see #22). If the TLS endpoint is not trusted, it could intercept the manifest of the host, and the content of the registry catalogue, and replace any keys contained therein with its own. Thus breaking any encryption method.

Therefore, the keys used by the registry should be certified by a CA, and the CN and CA used should be published, either in the catalogue itself or through a different channel. Then when a host opts to use an untrusted proxy, it can first determine the CA without going through the proxy. Using this certificate, his client can verify both the contents of the registry, and, by comparing his keys with those in the registry, that his manifest has not been tampered with.

**Comment by wrygiel** [comment]
We talked about this with Bavo in Warsaw.

We came up with the following solution:

* We could include a public RSA key directly in the Registry API specification.
* The Registry Service would use this key to sign all of its catalogue responses with HTTP Signatures. The Registry may sign such response every minute or so, and cache the signature along the catalogue response.
* Clients which don't trust TLS would have the option to verify the signature. This verification should not be a requirement for all clients, because:
  - many of them can actually trust TLS,
  - if it so happened that the private key is leaked, only some clients would need to be modified (the ones that don't trust TLS).

This public key would be hardcoded in our Registry Client implementation, but would not be verified by default:
* The caller should be able to change the hardcoded key by calling some method of the `RegistryClient`. This would enable the callers to quickly fix the leaked private key issue, before the Registry Client library gets updated and pushed to Maven.
* The caller should be able to enable signature verification during the construction of the client, or by calling some method of the `RegistryClient`.

**Comment by wrygiel** [comment]
Easy alternative: We require clients which cannot trust TLS to keep their own (e.g. hardcoded) set of root certificates, acquired directly from the registry maintainer, and update them from time to time. This may be a single root certificate, or a couple of them.

**Comment by wrygiel** [comment]
Two reasons to use the easy alternative:

* I will probably not be able to implement the HTTP Signatures before the end of the week. It seemed easy at first, but then I remembered that we use ETags for HTTP 304 responses, and such HTTP 304 would also need to be signed. This would require the implementer to understand Spring's filters in more detail (or rewriting them, which would probably be much easier). Unfortunately, I have other things to do too.

* I don't think there are many clients who would really need this extra security feature. All new operating systems come with proper root certificates, and keep them updated. And client's outgoing TLS connection is usually secured from the beginning, so it doesn't go unencrypted even via internal network.

**Comment by BavoNootaert** [comment]
Could you explain in more detail how that would be secure?

**Comment by murat-yuceer** [comment]
I guess my think,
Client => Server
Step1-Client will encrypt body content with server public key (for prevent sniff)
Step2-Client will encrypt, encrypted body content again with client private key (for authentication)
Step3-Client will add client public key to header
Server side
Step1-Server decrypt body content with client public key (if ok client trusted)
Setp2-Server decrypt again decrypted data with server private key
Server response
Step1-Server will encrypt response content data with client public key
Step2-Client will decrypt response content with client private key

**Comment by janinamincer-daszkiewicz** [comment]
TLS has been discontinued.
